#!/bin/bash
# Build the container
docker build -t libwally-wasm https://github.com/tiero/docker-libwally-wasm
# Run the container
docker run --name linux-build -d -i libwally-wasm
# Copy the custom build script inside the container
docker cp build_wasm.sh linux-build:/app/libwally-core/tools
# Run the build script
docker exec linux-build bash ./tools/build_wasm.sh
# Copy the artifacts from the contianer to local directory
mkdir -p dist
docker cp linux-build:/app/libwally-core/wallycore.js ./dist 
docker cp linux-build:/app/libwally-core/wallycore.html ./dist
docker cp linux-build:/app/libwally-core/wallycore.wasm ./dist

docker stop linux-build
docker rm linux-build
docker rmi libwally-wasm